#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 30 09:35:19 2019

@author: camillelamy
"""
import pandas as pd
import os


df = pd.read_csv(os.getcwd()+"/data/df/df_vecteur_revu.csv")

list_ISNN = df['2_ISSN'].tolist()

a = list_ISNN.count('03043800')
b = list_ISNN.count('01912615')
c = list_ISNN.count('1460-7425')
d = list_ISNN.count('none')




print (a,b,c,d)
